---
# This play installs the rhel-system-roles
# Playbooks referencing the rhel-system-roles will not
# execute until these are installed.


- name: "Install rhel-system-roles for ansible"
  become: true
  hosts: bastion
  
  tasks:

  - name: "Install the package"
    yum:
      name: 
        - "rhel-system-roles"
        - "ansible-collection-microsoft-sql"
      state: "latest"
